### ISSUE TITLE
使用问题

### ISSUE THREAD

**Issue by Dy-888** [ytu-shh/campusHelp#1]
请问你的管理员用户名及登录密码是啥？

**Comment by ytu-shh** [comment]
在admin表中插入数据即可，没有进行密码加密

**Comment by xCrank** [comment]
可以帮忙部署一下吗。

**Comment by ytu-shh** [comment]
qq 296943773 和我联系吧

**Comment by supremevirus** [comment]
没看到数据库文件，数据库是要自己建吗？

**Comment by ytu-shh** [comment]
在webconten/db目录下，觉得好记得打个star




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ytu-shh/campusHelp"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月25日(星期三) 晚上7:22
收件人:&nbsp;"ytu-shh/campusHelp"<campusHelp@noreply.github.com&gt;;
抄送:&nbsp;"296943773"<296943773@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [ytu-shh/campusHelp] 使用问题 (#1)





 
没看到数据库文件，数据库是要自己建吗？
