### ISSUE TITLE
运行问题

### ISSUE THREAD

**Issue by Dy-888** [ytu-shh/campusHelp#2]
请问管理员登录名和登录密码是多少？admin123456是错的

**Comment by zr6b** [comment]
> 请问管理员登录名和登录密码是多少？admin123456是错的

想问下你怎么连上数据库的

**Comment by ytu-shh** [comment]
在admin表中插入数据即可，没有对密码进行加密

**Comment by ytu-shh** [comment]
连数据需要现安装mysql 建议5.6/5.7版本，创建数据库，执行webContent/db/下的sql文件。具体度娘有很多
